name: openai_apps_sdk
description: A Flutter/Dart package that provides seamless integration with OpenAI's Apps SDK for ChatGPT, enabling developers to build interactive widgets and applications that run natively inside ChatGPT conversations.
version: 0.1.0+1

environment:
  sdk: ^3.9.0

dependencies:
  # Web
  html: ^0.15.6
  web: ^1.1.1

  # Freezed
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.9.0
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  test: ^1.26.3
  very_good_analysis: ^10.0.0
